prefixes:
  # default
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  owl: http://www.w3.org/2002/07/owl#
  xsd: http://www.w3.org/2001/XMLSchema#
  # functions
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
  # vocabulary for our entities and predicates
  schema: "https://schema.org/"
  dbo: http://dbpedia.org/ontology/
  fo: "https://www.bbc.co.uk/ontologies/fo/"  # food ontology with recipe, ingredient, ... all we need
  rev: "http://purl.org/stuff/rev#"           # reviews
  wd: https://www.wikidata.org/wiki/
  food: "http://data.lirmm.fr/ontologies/food#"
  ex: "http://example.org/"
  essglobal: "http://purl.org/essglobal/vocab/"

  # our own namespace
  # using ken instead of example.org as our own namespace
  # on w3id due to "Permanent Identifiers for the Web"
  ken: "https://w3id.org/um/ken4256/"


mappings:
  recipe:
    sources:
      - ['products.json~jsonpath', "$.products[*]"]
    s: ken:product/$(code)
    po:
      - [a, schema:Product]
      - [rdfs:label, $(product_name)]
      - [ken:mainCategory, ken:category/$(main_category)~iri]
      - [fo:shopping_category, ken:category/$(categories)~iri]
      - [essglobal:isAvailableAt, ken:country/$(countries)~iri]
      - [fo:ingredients, ken:ingredient/$(ingredients)~iri]
      - [food:nutritionScoreFrPer100g, ken:nutriscore/$(nutriscore_grade)~iri]
      # - [food:nutritionGradeFrPer100g, $(nutriscore_grade)]
      # - [food:novaGroupPer100g, $(nova_group)]
      - [schema:calories, $(energy_kcal_100g), xsd:decimal]
      - [schema:fiberContent, $(fat_100g), xsd:decimal]
      - [schema:unsaturatedFatContent, $(saturated_fat_100g), xsd:decimal]
      - [schema:transFatContent, $(trans_fat_100g), xsd:decimal]
      - [schema:cholesterolContent, $(cholesterol_100g), xsd:decimal]
      - [schema:carbohydrateContent, $(carbohydrates_100g), xsd:decimal]
      - [schema:sugarContent, $(sugars_100g), xsd:decimal]
      - [schema:fiberContent, $(fiber_100g), xsd:decimal]
      - [schema:proteinContent, $(proteins_100g), xsd:decimal]
      - [food:saltPer100g, $(salt_100g), xsd:decimal]
      - [schema:sodiumContent, $(sodium_100g), xsd:decimal]